### ISSUE TITLE
Active scan: java.lang.NullPointerException

### ISSUE THREAD

**Issue by antnks** [antnks/wcf-deserializer#11]
There are bunch of java.lang.NullPointerException logged into Error tab of the extension during the active scan

**Comment by antnks** [comment]
```
java.lang.NullPointerException
	at burp.WCFUtils.isWCF(WCFUtils.java:123)
	at burp.WCFHttpListener.processHttpMessage(WCFHttpListener.java:75)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
